### PR TITLE
upgrade to serde 1.0

### PR DESCRIPTION
**Pull request by euclio**
This PR modifies the serialization logic to reuse `serde_json`'s by converting `Variable` to `Value` before serialization.

This change requires a SemVer bump.

### CODE REVIEW

**Comment by mtdowling** [comment]
Thanks for working on this PR.

Does this have any performance implications (e.g., converting first to Value then serializing)?

**Comment by euclio** [comment]
Hm, just ran the benchmarks on my computer and it appears that there is a significant performance hit. I'm not sure if it's the way my logic works or serde itself, though.

**Comment by euclio** [comment]
@mtdowling would you rather patch this as-is or shall I make a PR that implements Serialize/Deserialize directly?

**Comment by mtdowling** [comment]
One of the main reasons for creating a Rust version of JMESPath was to make it as fast as possible. I do think it is worth the added complexity and maintenance to implement Serialize/Deserialize directly.

If you are willing to implement that, that would be awesome!

**Comment by euclio** [comment]
Closing due to #24 being merged.

**Pull request closed without merging**
