### PR TITLE
Sfr/test debugging

### PR DESCRIPTION
**Pull request by silvio**

### CODE REVIEW

**Comment by mtdowling** [comment]
Is this a work in progress PR? What is this for?

**Comment by silvio** [comment]
This will show you that not all tests pass the compliance test. #16 have me showed that something is wrong with the compliance test. With this PR I *mean* to show which test are going wrong.

**Comment by mtdowling** [comment]
I synced up with the latest compliance tests in https://github.com/mtdowling/jmespath.rs/commit/9e4824b18a2d9f92e9d477b27eb94c15219f6b55, and I was able to pass every test. Resolving as I can't reproduce.

**Comment by silvio** [comment]
Is #16 fixed?

**Pull request closed without merging**
